---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

#NEW: (START) ##########################################################
permissions:
  pull-requests: write # needed to create and update comments in PRs
#NEW: (END) ############################################################

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest    
    steps:
            
      -  name: Login to GHCR
         uses: docker/login-action@v2
         with:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Docker build
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/ode-to-gitops/wordsmith-web:latest
